### ISSUE TITLE
AttributeError: 'configuration' object has no attribute 'io_file'

### ISSUE THREAD

**Issue by Casthardi** [C2SM-RCM/testsuite#12]
I got this error message when running the test suite.
Adding the following line in testsuite.py after line 52 solves this issue for me
        conf.io_file     = config.get('ts_config','io_file')
Burkhardt

**Comment by lxavier** [comment]
thanks, I actually just seen the error as well on our new system, no idea why we have not seen the error before. I will merge the change asap

**Comment by lxavier** [comment]
https://github.com/C2SM-RCM/testsuite/pull/13/files

**Comment by kosterried** [comment]
This issue was resolved with PR #13
